### ISSUE TITLE
Significance of the different colors of yolk

### ISSUE THREAD

**Issue by lgtout** [overfullstack/railway-oriented-validation-kotlin#1]
Hi,

Thanks for sharing this project.  I have some questions that will help me understand it better.
What's the significance of the different colors of yolk?  Does the yolk color change over time?  Is there a relationship between yolk color and days-to-hatch?

Thanks!

**Comment by lgtout** [comment]
Oh, I just came upon `Rules.kt`.  I see there's no relationship between days-to-hatch and yolk color.  And that there's no difference between `GOLD` and `YELLOW` in terms of success.

**Comment by overfullstack** [comment]
Hey @lgtout yes you are right, there is no significance. Those are all some dummy rules to demostrate the design. You may change and play with them. The problem is the Expected Dataset for Unit tests is tightly coupled with the rules. I have been thinking of making is more flexible. But if you got any idea, I would love to see any suggestions or contributions. Thank you :)
